// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ArchivePageDocumentDataSlicesSlice = ContentSliceSlice

/**
 * Content for Archive Page documents
 */
interface ArchivePageDocumentData {
    /**
   * Title field in *Archive Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *Archive Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField

    /**
   * Image field in *Archive Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * Slice Zone field in *Archive Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices: prismic.SliceZone<ArchivePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Archive Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: archive_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_title: prismic.KeyTextField

    /**
   * Meta Description field in *Archive Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archive_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_description: prismic.KeyTextField

    /**
   * Meta Image field in *Archive Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    meta_image: prismic.ImageField<never>
}

/**
 * Archive Page document from Prismic
 *
 * - **API ID**: `archive_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchivePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
      Simplify<ArchivePageDocumentData>,
      'archive_page',
      Lang
  >

type DefaultPageDocumentDataSlicesSlice = never

/**
 * Content for Default page documents
 */
interface DefaultPageDocumentData {
    /**
   * Title field in *Default page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *Default page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField

    /**
   * Image field in *Default page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * Slice Zone field in *Default page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices: prismic.SliceZone<DefaultPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Default page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: default_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_title: prismic.KeyTextField

    /**
   * Meta Description field in *Default page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: default_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_description: prismic.KeyTextField

    /**
   * Meta Image field in *Default page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    meta_image: prismic.ImageField<never>
}

/**
 * Default page document from Prismic
 *
 * - **API ID**: `default_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
      Simplify<DefaultPageDocumentData>,
      'default_page',
      Lang
  >

/**
 * Item in *Footer menu → Links*
 */
export interface FooterMenuDocumentDataLinksItem {
    /**
   * Label field in *Footer menu → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    label: prismic.KeyTextField

    /**
   * Internal page field in *Footer menu → Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.links[].internal_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    internal_page: prismic.ContentRelationshipField<
        | 'default_page'
        | 'home_page'
        | 'project_page'
        | 'project_listing_page'
        | 'archive_page'
    >

    /**
   * external url field in *Footer menu → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.links[].external_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    external_url: prismic.KeyTextField
}

/**
 * Content for Footer menu documents
 */
interface FooterMenuDocumentData {
    /**
   * Links field in *Footer menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    links: prismic.GroupField<Simplify<FooterMenuDocumentDataLinksItem>>
}

/**
 * Footer menu document from Prismic
 *
 * - **API ID**: `footer_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
      Simplify<FooterMenuDocumentData>,
      'footer_menu',
      Lang
  >

/**
 * Item in *Home page → media*
 */
export interface HomePageDocumentDataMediaItem {
    /**
   * image field in *Home page → media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.media[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * video embed field in *Home page → media*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.media[].video_embed
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
    video_embed: prismic.EmbedField
}

type HomePageDocumentDataSlicesSlice =
    | ServicesSliceSlice
    | ProjectFeedSliceSlice
    | ContentSliceSlice
    | ContactSliceSlice

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
    /**
   * Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * tagline field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    tagline: prismic.KeyTextField

    /**
   * location field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    location: prismic.KeyTextField

    /**
   * media field in *Home page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    media: prismic.GroupField<Simplify<HomePageDocumentDataMediaItem>>

    /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_title: prismic.KeyTextField

    /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_description: prismic.KeyTextField

    /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    meta_image: prismic.ImageField<never>
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
      Simplify<HomePageDocumentData>,
      'home_page',
      Lang
  >

/**
 * Item in *Menu → links*
 */
export interface MenuDocumentDataLinksItem {
    /**
   * Label field in *Menu → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    label: prismic.KeyTextField

    /**
   * Internal page field in *Menu → links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[].internal_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    internal_page: prismic.ContentRelationshipField<
        | 'home_page'
        | 'default_page'
        | 'project_listing_page'
        | 'project_page'
        | 'archive_page'
    >

    /**
   * External url field in *Menu → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[].external_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    external_url: prismic.KeyTextField
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
    /**
   * Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * links field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    links: prismic.GroupField<Simplify<MenuDocumentDataLinksItem>>
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, 'menu', Lang>

type ProjectListingPageDocumentDataSlicesSlice = never

/**
 * Content for Project listing page documents
 */
interface ProjectListingPageDocumentData {
    /**
   * Title field in *Project listing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *Project listing page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField

    /**
   * Image field in *Project listing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * Slice Zone field in *Project listing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices: prismic.SliceZone<ProjectListingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Project listing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_listing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_title: prismic.KeyTextField

    /**
   * Meta Description field in *Project listing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_listing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_description: prismic.KeyTextField

    /**
   * Meta Image field in *Project listing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    meta_image: prismic.ImageField<never>
}

/**
 * Project listing page document from Prismic
 *
 * - **API ID**: `project_listing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectListingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
      Simplify<ProjectListingPageDocumentData>,
      'project_listing_page',
      Lang
  >

/**
 * Item in *Project page → link*
 */
export interface ProjectPageDocumentDataLinkItem {
    /**
   * label field in *Project page → link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    label: prismic.KeyTextField

    /**
   * link field in *Project page → link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

type ProjectPageDocumentDataSlicesSlice = never

type ProjectPageDocumentDataSlices2Slice = ContentSliceSlice

/**
 * Content for Project page documents
 */
interface ProjectPageDocumentData {
    /**
   * Title field in *Project page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *Project page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField

    /**
   * Image field in *Project page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * Archived field in *Project page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: project_page.archived
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
    archived: prismic.BooleanField

    /**
   * Order date field in *Project page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date utilisée pour l'ordre d'affichage
   * - **API ID Path**: project_page.order_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
    order_date: prismic.DateField

    /**
   * Creation date field in *Project page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.creation_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
    creation_date: prismic.DateField

    /**
   * link field in *Project page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    link: prismic.GroupField<Simplify<ProjectPageDocumentDataLinkItem>>

    /**
   * Credits field in *Project page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.credits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    credits: prismic.RichTextField

    /**
   * Slice Zone field in *Project page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Project page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_title: prismic.KeyTextField

    /**
   * Meta Description field in *Project page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    meta_description: prismic.KeyTextField

    /**
   * Meta Image field in *Project page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *Project page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.slices2[]
   * - **Tab**: Slices
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
    slices2: prismic.SliceZone<ProjectPageDocumentDataSlices2Slice>
}

/**
 * Project page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
      Simplify<ProjectPageDocumentData>,
      'project_page',
      Lang
  >

/**
 * Item in *settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
    /**
   * Label field in *settings → Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    label: prismic.KeyTextField

    /**
   * External url field in *settings → Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].external_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    external_url: prismic.KeyTextField

    /**
   * Icon field in *settings → Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
    icon: prismic.SelectField<
        | 'instagram'
        | 'facebook'
        | 'x'
        | 'tiktok'
        | 'vimeo'
        | 'behance'
        | 'youtube'
        | 'linkedin'
    >

    /**
   * Show in contact slice field in *settings → Socials*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.socials[].show_in_contact_slice
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
    show_in_contact_slice: prismic.BooleanField
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
    /**
   * Site name field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Mon site
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    site_name: prismic.KeyTextField

    /**
   * Email field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    email: prismic.KeyTextField

    /**
   * Socials field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>

    /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    logo: prismic.ImageField<never>

    /**
   * showreel field in *settings*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.showreel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    showreel: prismic.LinkToMediaField<prismic.FieldState, never>
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
      Simplify<SettingsDocumentData>,
      'settings',
      Lang
  >

export type AllDocumentTypes =
    | ArchivePageDocument
    | DefaultPageDocument
    | FooterMenuDocument
    | HomePageDocument
    | MenuDocument
    | ProjectListingPageDocument
    | ProjectPageDocument
    | SettingsDocument

/**
 * Item in *ContactSlice → Default → Primary → Body*
 */
export interface ContactSliceSliceDefaultPrimaryBodyItem {
    /**
   * Title field in *ContactSlice → Default → Primary → Body*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.body[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *ContactSlice → Default → Primary → Body*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.body[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField
}

/**
 * Item in *ContactSlice → Default → Primary → Link group*
 */
export interface ContactSliceSliceDefaultPrimaryLinkGroupItem {
    /**
   * label field in *ContactSlice → Default → Primary → Link group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.link_group[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    label: prismic.KeyTextField

    /**
   * Link field in *ContactSlice → Default → Primary → Link group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.link_group[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Primary content in *ContactSlice → Default → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
    /**
   * Title field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Body field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.body[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    body: prismic.GroupField<Simplify<ContactSliceSliceDefaultPrimaryBodyItem>>

    /**
   * Link group field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.default.primary.link_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    link_group: prismic.GroupField<
        Simplify<ContactSliceSliceDefaultPrimaryLinkGroupItem>
    >
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContactSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSlice = prismic.SharedSlice<
    'contact_slice',
    ContactSliceSliceVariation
>

/**
 * Item in *ContentSlice → Default → Primary → Contents*
 */
export interface ContentSliceSliceDefaultPrimaryContentsItem {
    /**
   * Embed video url field in *ContentSlice → Default → Primary → Contents*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[].embed_video_url
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
    embed_video_url: prismic.EmbedField

    /**
   * Image field in *ContentSlice → Default → Primary → Contents*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
    image: prismic.ImageField<never>

    /**
   * Text field in *ContentSlice → Default → Primary → Contents*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    text: prismic.RichTextField

    /**
   * External_url field in *ContentSlice → Default → Primary → Contents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[].external_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    external_url: prismic.KeyTextField

    /**
   * Link label field in *ContentSlice → Default → Primary → Contents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    link_label: prismic.KeyTextField
}

/**
 * Primary content in *ContentSlice → Default → Primary*
 */
export interface ContentSliceSliceDefaultPrimary {
    /**
   * Contents field in *ContentSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_slice.default.primary.contents[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    contents: prismic.GroupField<
        Simplify<ContentSliceSliceDefaultPrimaryContentsItem>
    >
}

/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContentSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ContentSlice*
 */
type ContentSliceSliceVariation = ContentSliceSliceDefault

/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSlice = prismic.SharedSlice<
    'content_slice',
    ContentSliceSliceVariation
>

/**
 * Item in *ProjectFeedSlice → Default → Primary → Custom projects*
 */
export interface ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem {
    /**
   * Project field in *ProjectFeedSlice → Default → Primary → Custom projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.custom_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    project: prismic.ContentRelationshipField<'project_page'>
}

/**
 * Primary content in *ProjectFeedSlice → Default → Primary*
 */
export interface ProjectFeedSliceSliceDefaultPrimary {
    /**
   * Title field in *ProjectFeedSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Internal page field in *ProjectFeedSlice → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.internal_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    internal_page: prismic.ContentRelationshipField<'project_listing_page'>

    /**
   * Link label field in *ProjectFeedSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    link_label: prismic.KeyTextField

    /**
   * Externa url field in *ProjectFeedSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.externa_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    externa_url: prismic.KeyTextField

    /**
   * Custom projects field in *ProjectFeedSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_feed_slice.default.primary.custom_projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    custom_projects: prismic.GroupField<
        Simplify<ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem>
    >
}

/**
 * Default variation for ProjectFeedSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectFeedSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ProjectFeedSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ProjectFeedSlice*
 */
type ProjectFeedSliceSliceVariation = ProjectFeedSliceSliceDefault

/**
 * ProjectFeedSlice Shared Slice
 *
 * - **API ID**: `project_feed_slice`
 * - **Description**: ProjectFeedSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectFeedSliceSlice = prismic.SharedSlice<
    'project_feed_slice',
    ProjectFeedSliceSliceVariation
>

/**
 * Item in *ServicesSlice → Default → Primary → Services*
 */
export interface ServicesSliceSliceDefaultPrimaryServicesItem {
    /**
   * Title field in *ServicesSlice → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Content field in *ServicesSlice → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.services[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
    content: prismic.RichTextField
}

/**
 * Primary content in *ServicesSlice → Default → Primary*
 */
export interface ServicesSliceSliceDefaultPrimary {
    /**
   * Title field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    title: prismic.KeyTextField

    /**
   * Link label field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    link_label: prismic.KeyTextField

    /**
   * External url field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.external_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
    external_url: prismic.KeyTextField

    /**
   * Internal page field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.internal_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
    internal_page: prismic.ContentRelationshipField<
        | 'archive_page'
        | 'home_page'
        | 'default_page'
        | 'project_listing_page'
        | 'project_page'
    >

    /**
   * Services field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
    services: prismic.GroupField<
        Simplify<ServicesSliceSliceDefaultPrimaryServicesItem>
    >
}

/**
 * Default variation for ServicesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ServicesSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ServicesSlice*
 */
type ServicesSliceSliceVariation = ServicesSliceSliceDefault

/**
 * ServicesSlice Shared Slice
 *
 * - **API ID**: `services_slice`
 * - **Description**: ServicesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSlice = prismic.SharedSlice<
    'services_slice',
    ServicesSliceSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig,
        ): prismic.Client<AllDocumentTypes>
    }

    interface CreateWriteClient {
        (
            repositoryNameOrEndpoint: string,
            options: prismic.WriteClientConfig,
        ): prismic.WriteClient<AllDocumentTypes>
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>
    }

    namespace Content {
        export type {
            ArchivePageDocument,
            ArchivePageDocumentData,
            ArchivePageDocumentDataSlicesSlice,
            DefaultPageDocument,
            DefaultPageDocumentData,
            DefaultPageDocumentDataSlicesSlice,
            FooterMenuDocument,
            FooterMenuDocumentData,
            FooterMenuDocumentDataLinksItem,
            HomePageDocument,
            HomePageDocumentData,
            HomePageDocumentDataMediaItem,
            HomePageDocumentDataSlicesSlice,
            MenuDocument,
            MenuDocumentData,
            MenuDocumentDataLinksItem,
            ProjectListingPageDocument,
            ProjectListingPageDocumentData,
            ProjectListingPageDocumentDataSlicesSlice,
            ProjectPageDocument,
            ProjectPageDocumentData,
            ProjectPageDocumentDataLinkItem,
            ProjectPageDocumentDataSlicesSlice,
            ProjectPageDocumentDataSlices2Slice,
            SettingsDocument,
            SettingsDocumentData,
            SettingsDocumentDataSocialsItem,
            AllDocumentTypes,
            ContactSliceSlice,
            ContactSliceSliceDefaultPrimaryBodyItem,
            ContactSliceSliceDefaultPrimaryLinkGroupItem,
            ContactSliceSliceDefaultPrimary,
            ContactSliceSliceVariation,
            ContactSliceSliceDefault,
            ContentSliceSlice,
            ContentSliceSliceDefaultPrimaryContentsItem,
            ContentSliceSliceDefaultPrimary,
            ContentSliceSliceVariation,
            ContentSliceSliceDefault,
            ProjectFeedSliceSlice,
            ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem,
            ProjectFeedSliceSliceDefaultPrimary,
            ProjectFeedSliceSliceVariation,
            ProjectFeedSliceSliceDefault,
            ServicesSliceSlice,
            ServicesSliceSliceDefaultPrimaryServicesItem,
            ServicesSliceSliceDefaultPrimary,
            ServicesSliceSliceVariation,
            ServicesSliceSliceDefault,
        }
    }
}
