// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ArchivePageDocumentDataSlicesSlice = ContentSliceSlice

/**
 * Content for Archive Page documents
 */
interface ArchivePageDocumentData {
    /**
     * Title field in *Archive Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: archive_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *Archive Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: archive_page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Image field in *Archive Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: archive_page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Slice Zone field in *Archive Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: archive_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ArchivePageDocumentDataSlicesSlice> /**
     * Meta Title field in *Archive Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: archive_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */

    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Archive Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: archive_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Archive Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: archive_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>
}

/**
 * Archive Page document from Prismic
 *
 * - **API ID**: `archive_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchivePageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<ArchivePageDocumentData>,
        'archive_page',
        Lang
    >

type DefaultPageDocumentDataSlicesSlice = never

/**
 * Content for Default page documents
 */
interface DefaultPageDocumentData {
    /**
     * Title field in *Default page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: default_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *Default page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: default_page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Image field in *Default page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: default_page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Slice Zone field in *Default page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: default_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<DefaultPageDocumentDataSlicesSlice> /**
     * Meta Title field in *Default page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: default_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */

    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Default page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: default_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Default page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: default_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>
}

/**
 * Default page document from Prismic
 *
 * - **API ID**: `default_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultPageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<DefaultPageDocumentData>,
        'default_page',
        Lang
    >

type HomePageDocumentDataSlicesSlice = never

type HomePageDocumentDataSlices2Slice =
    | ServicesSliceSlice
    | IntroSliceSlice
    | ProjectFeedSliceSlice
    | AboutSliceSlice
    | ContactSliceSlice
    | ContentSliceSlice

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
    /**
     * Title field in *Home page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *Home page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    content: prismic.KeyTextField

    /**
     * Image field in *Home page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Slice Zone field in *Home page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
     * Meta Title field in *Home page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */

    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Home page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Home page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never> /**
     * Slice Zone field in *Home page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices2[]
     * - **Tab**: Slices
     * - **Documentation**: https://prismic.io/docs/field#slices
     */

    slices2: prismic.SliceZone<HomePageDocumentDataSlices2Slice>
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<HomePageDocumentData>,
        'home_page',
        Lang
    >

/**
 * Item in *Menu → links*
 */
export interface MenuDocumentDataLinksItem {
    /**
     * Label field in *Menu → links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.links[].label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    label: prismic.KeyTextField

    /**
     * Internal page field in *Menu → links*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.links[].internal_page
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    internal_page: prismic.ContentRelationshipField<
        | 'home_page'
        | 'default_page'
        | 'project_listing_page'
        | 'project_page'
        | 'archive_page'
    >

    /**
     * External url field in *Menu → links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.links[].external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
    /**
     * Title field in *Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * links field in *Menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    links: prismic.GroupField<Simplify<MenuDocumentDataLinksItem>>
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, 'menu', Lang>

type ProjectListingPageDocumentDataSlicesSlice = never

/**
 * Content for Project listing page documents
 */
interface ProjectListingPageDocumentData {
    /**
     * Title field in *Project listing page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_listing_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *Project listing page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_listing_page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Image field in *Project listing page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_listing_page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Slice Zone field in *Project listing page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project_listing_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProjectListingPageDocumentDataSlicesSlice> /**
     * Meta Title field in *Project listing page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: project_listing_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */

    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Project listing page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: project_listing_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Project listing page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_listing_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>
}

/**
 * Project listing page document from Prismic
 *
 * - **API ID**: `project_listing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectListingPageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<ProjectListingPageDocumentData>,
        'project_listing_page',
        Lang
    >

/**
 * Item in *Project page → Attributes*
 */
export interface ProjectPageDocumentDataAttributesItem {
    /**
     * Label field in *Project page → Attributes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.attributes[].label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    label: prismic.KeyTextField

    /**
     * Content field in *Project page → Attributes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.attributes[].content
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    content: prismic.KeyTextField
}

type ProjectPageDocumentDataSlicesSlice = never

type ProjectPageDocumentDataSlices2Slice = ContentSliceSlice

/**
 * Content for Project page documents
 */
interface ProjectPageDocumentData {
    /**
     * Title field in *Project page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *Project page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Short content field in *Project page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.short_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    short_content: prismic.KeyTextField

    /**
     * Image field in *Project page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Archived field in *Project page*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: project_page.archived
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    archived: prismic.BooleanField

    /**
     * Creation date field in *Project page*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.creation_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    creation_date: prismic.DateField

    /**
     * External url field in *Project page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.external_url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Attributes field in *Project page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.attributes[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    attributes: prismic.GroupField<
        Simplify<ProjectPageDocumentDataAttributesItem>
    >

    /**
     * Slice Zone field in *Project page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice> /**
     * Meta Title field in *Project page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: project_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */

    meta_title: prismic.KeyTextField

    /**
     * Meta Description field in *Project page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: project_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Project page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never> /**
     * Slice Zone field in *Project page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project_page.slices2[]
     * - **Tab**: Slices
     * - **Documentation**: https://prismic.io/docs/field#slices
     */

    slices2: prismic.SliceZone<ProjectPageDocumentDataSlices2Slice>
}

/**
 * Project page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ProjectPageDocumentData>,
        'project_page',
        Lang
    >

/**
 * Item in *settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
    /**
     * Label field in *settings → Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.socials[].label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    label: prismic.KeyTextField

    /**
     * External url field in *settings → Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.socials[].external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Icon field in *settings → Socials*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.socials[].icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    icon: prismic.SelectField<
        | 'instagram'
        | 'facebook'
        | 'x'
        | 'tiktok'
        | 'vimeo'
        | 'behance'
        | 'youtube'
        | 'linkedin'
    >
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
    /**
     * Site name field in *settings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Mon site
     * - **API ID Path**: settings.site_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    site_name: prismic.KeyTextField

    /**
     * Email field in *settings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    email: prismic.KeyTextField

    /**
     * Socials field in *settings*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.socials[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>

    /**
     * logo field in *settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logo: prismic.ImageField<never>

    /**
     * showreel field in *settings*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.showreel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    showreel: prismic.LinkToMediaField
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<SettingsDocumentData>,
        'settings',
        Lang
    >

export type AllDocumentTypes =
    | ArchivePageDocument
    | DefaultPageDocument
    | HomePageDocument
    | MenuDocument
    | ProjectListingPageDocument
    | ProjectPageDocument
    | SettingsDocument

/**
 * Primary content in *AboutSlice → Default → Primary*
 */
export interface AboutSliceSliceDefaultPrimary {
    /**
     * Title field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Image field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Link label field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.link_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link_label: prismic.KeyTextField

    /**
     * External url field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Internal page field in *AboutSlice → Default → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: about_slice.default.primary.internal_page
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    internal_page: prismic.ContentRelationshipField
}

/**
 * Default variation for AboutSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<AboutSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *AboutSlice*
 */
type AboutSliceSliceVariation = AboutSliceSliceDefault

/**
 * AboutSlice Shared Slice
 *
 * - **API ID**: `about_slice`
 * - **Description**: AboutSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceSlice = prismic.SharedSlice<
    'about_slice',
    AboutSliceSliceVariation
>

/**
 * Item in *ContactSlice → Default → Primary → Attributs*
 */
export interface ContactSliceSliceDefaultPrimaryAttributsItem {
    /**
     * Label field in *ContactSlice → Default → Primary → Attributs*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.attributs[].label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    label: prismic.KeyTextField

    /**
     * External url field in *ContactSlice → Default → Primary → Attributs*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.attributs[].external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Icon field in *ContactSlice → Default → Primary → Attributs*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.attributs[].icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    icon: prismic.SelectField<'Email' | 'Phone'>
}

/**
 * Primary content in *ContactSlice → Default → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
    /**
     * Title field in *ContactSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *ContactSlice → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Attributs field in *ContactSlice → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_slice.default.primary.attributs[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    attributs: prismic.GroupField<
        Simplify<ContactSliceSliceDefaultPrimaryAttributsItem>
    >
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContactSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSlice = prismic.SharedSlice<
    'contact_slice',
    ContactSliceSliceVariation
>

/**
 * Item in *ContentSlice → Default → Primary → Contents*
 */
export interface ContentSliceSliceDefaultPrimaryContentsItem {
    /**
     * Embed video url field in *ContentSlice → Default → Primary → Contents*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[].embed_video_url
     * - **Documentation**: https://prismic.io/docs/field#embed
     */
    embed_video_url: prismic.EmbedField

    /**
     * Image field in *ContentSlice → Default → Primary → Contents*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>

    /**
     * Text field in *ContentSlice → Default → Primary → Contents*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[].text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField

    /**
     * External_url field in *ContentSlice → Default → Primary → Contents*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[].external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Link label field in *ContentSlice → Default → Primary → Contents*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[].link_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link_label: prismic.KeyTextField
}

/**
 * Primary content in *ContentSlice → Default → Primary*
 */
export interface ContentSliceSliceDefaultPrimary {
    /**
     * Contents field in *ContentSlice → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.default.primary.contents[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    contents: prismic.GroupField<
        Simplify<ContentSliceSliceDefaultPrimaryContentsItem>
    >
}

/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContentSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ContentSlice*
 */
type ContentSliceSliceVariation = ContentSliceSliceDefault

/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: ContentSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceSlice = prismic.SharedSlice<
    'content_slice',
    ContentSliceSliceVariation
>

/**
 * Item in *IntroSlice → Default → Primary → attributes*
 */
export interface IntroSliceSliceDefaultPrimaryAttributesItem {
    /**
     * attribut field in *IntroSlice → Default → Primary → attributes*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_slice.default.primary.attributes[].attribut
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    attribut: prismic.KeyTextField
}

/**
 * Primary content in *IntroSlice → Default → Primary*
 */
export interface IntroSliceSliceDefaultPrimary {
    /**
     * title field in *IntroSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_slice.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *IntroSlice → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_slice.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField

    /**
     * Secondary title field in *IntroSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_slice.default.primary.secondary_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    secondary_title: prismic.KeyTextField

    /**
     * attributes field in *IntroSlice → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_slice.default.primary.attributes[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    attributes: prismic.GroupField<
        Simplify<IntroSliceSliceDefaultPrimaryAttributesItem>
    >
}

/**
 * Default variation for IntroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<IntroSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *IntroSlice*
 */
type IntroSliceSliceVariation = IntroSliceSliceDefault

/**
 * IntroSlice Shared Slice
 *
 * - **API ID**: `intro_slice`
 * - **Description**: IntroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSliceSlice = prismic.SharedSlice<
    'intro_slice',
    IntroSliceSliceVariation
>

/**
 * Item in *ProjectFeedSlice → Default → Primary → Custom projects*
 */
export interface ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem {
    /**
     * Project field in *ProjectFeedSlice → Default → Primary → Custom projects*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project_feed_slice.default.primary.custom_projects[].project
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    project: prismic.ContentRelationshipField<'project_page'>
}

/**
 * Primary content in *ProjectFeedSlice → Default → Primary*
 */
export interface ProjectFeedSliceSliceDefaultPrimary {
    /**
     * Title field in *ProjectFeedSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_feed_slice.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Internal page field in *ProjectFeedSlice → Default → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project_feed_slice.default.primary.internal_page
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    internal_page: prismic.ContentRelationshipField<'project_listing_page'>

    /**
     * Link label field in *ProjectFeedSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project_feed_slice.default.primary.link_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link_label: prismic.KeyTextField

    /**
     * Custom projects field in *ProjectFeedSlice → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: project_feed_slice.default.primary.custom_projects[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    custom_projects: prismic.GroupField<
        Simplify<ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem>
    >
}

/**
 * Default variation for ProjectFeedSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectFeedSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ProjectFeedSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ProjectFeedSlice*
 */
type ProjectFeedSliceSliceVariation = ProjectFeedSliceSliceDefault

/**
 * ProjectFeedSlice Shared Slice
 *
 * - **API ID**: `project_feed_slice`
 * - **Description**: ProjectFeedSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectFeedSliceSlice = prismic.SharedSlice<
    'project_feed_slice',
    ProjectFeedSliceSliceVariation
>

/**
 * Item in *ServicesSlice → Default → Primary → Services*
 */
export interface ServicesSliceSliceDefaultPrimaryServicesItem {
    /**
     * Title field in *ServicesSlice → Default → Primary → Services*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.services[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Content field in *ServicesSlice → Default → Primary → Services*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.services[].content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField
}

/**
 * Primary content in *ServicesSlice → Default → Primary*
 */
export interface ServicesSliceSliceDefaultPrimary {
    /**
     * Title field in *ServicesSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * Link label field in *ServicesSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.link_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link_label: prismic.KeyTextField

    /**
     * External url field in *ServicesSlice → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.external_url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_url: prismic.KeyTextField

    /**
     * Internal page field in *ServicesSlice → Default → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.internal_page
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    internal_page: prismic.ContentRelationshipField<
        | 'archive_page'
        | 'home_page'
        | 'default_page'
        | 'project_listing_page'
        | 'project_page'
    >

    /**
     * Services field in *ServicesSlice → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: services_slice.default.primary.services[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    services: prismic.GroupField<
        Simplify<ServicesSliceSliceDefaultPrimaryServicesItem>
    >
}

/**
 * Default variation for ServicesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ServicesSliceSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ServicesSlice*
 */
type ServicesSliceSliceVariation = ServicesSliceSliceDefault

/**
 * ServicesSlice Shared Slice
 *
 * - **API ID**: `services_slice`
 * - **Description**: ServicesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSlice = prismic.SharedSlice<
    'services_slice',
    ServicesSliceSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig,
        ): prismic.Client<AllDocumentTypes>
    }

    interface CreateWriteClient {
        (
            repositoryNameOrEndpoint: string,
            options: prismic.WriteClientConfig,
        ): prismic.WriteClient<AllDocumentTypes>
    }

    interface CreateMigration {
        (): prismic.Migration<AllDocumentTypes>
    }

    namespace Content {
        export type {
            ArchivePageDocument,
            ArchivePageDocumentData,
            ArchivePageDocumentDataSlicesSlice,
            DefaultPageDocument,
            DefaultPageDocumentData,
            DefaultPageDocumentDataSlicesSlice,
            HomePageDocument,
            HomePageDocumentData,
            HomePageDocumentDataSlicesSlice,
            HomePageDocumentDataSlices2Slice,
            MenuDocument,
            MenuDocumentData,
            MenuDocumentDataLinksItem,
            ProjectListingPageDocument,
            ProjectListingPageDocumentData,
            ProjectListingPageDocumentDataSlicesSlice,
            ProjectPageDocument,
            ProjectPageDocumentData,
            ProjectPageDocumentDataAttributesItem,
            ProjectPageDocumentDataSlicesSlice,
            ProjectPageDocumentDataSlices2Slice,
            SettingsDocument,
            SettingsDocumentData,
            SettingsDocumentDataSocialsItem,
            AllDocumentTypes,
            AboutSliceSlice,
            AboutSliceSliceDefaultPrimary,
            AboutSliceSliceVariation,
            AboutSliceSliceDefault,
            ContactSliceSlice,
            ContactSliceSliceDefaultPrimaryAttributsItem,
            ContactSliceSliceDefaultPrimary,
            ContactSliceSliceVariation,
            ContactSliceSliceDefault,
            ContentSliceSlice,
            ContentSliceSliceDefaultPrimaryContentsItem,
            ContentSliceSliceDefaultPrimary,
            ContentSliceSliceVariation,
            ContentSliceSliceDefault,
            IntroSliceSlice,
            IntroSliceSliceDefaultPrimaryAttributesItem,
            IntroSliceSliceDefaultPrimary,
            IntroSliceSliceVariation,
            IntroSliceSliceDefault,
            ProjectFeedSliceSlice,
            ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem,
            ProjectFeedSliceSliceDefaultPrimary,
            ProjectFeedSliceSliceVariation,
            ProjectFeedSliceSliceDefault,
            ServicesSliceSlice,
            ServicesSliceSliceDefaultPrimaryServicesItem,
            ServicesSliceSliceDefaultPrimary,
            ServicesSliceSliceVariation,
            ServicesSliceSliceDefault,
        }
    }
}
