// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_slice: defineAsyncComponent(() => import("./AboutSlice/index.vue")),
  contact_slice: defineAsyncComponent(() => import("./ContactSlice/index.vue")),
  content_slice: defineAsyncComponent(() => import("./ContentSlice/index.vue")),
  intro_slice: defineAsyncComponent(() => import("./IntroSlice/index.vue")),
  project_feed_slice: defineAsyncComponent(
    () => import("./ProjectFeedSlice/index.vue"),
  ),
});
